### ISSUE TITLE
Inadyn v1.99.14: pidfile is not created (regression)

### ISSUE THREAD

**Issue by daersc** [troglobit/inadyn#100]
Neither the inadyn.conf option pidfile nor the command line option --pidfile seems to work on my machine. No pid file will be created although running inadyn as root.

**Comment by troglobit** [comment]
OK, I'll look into it.  What version of Inadyn are you running, is it from a Linux distribution or a release from GitHub (or my FTP)?

Thank you for reporting!

**Comment by daersc** [comment]
I tried with the v1.99.14 from GitHub via
`$ ./configure --enable-openssl`
`$ make`
`# make install`
on Linux. The v1.99.13 works fine (after renaming ChangeLog).

**Comment by troglobit** [comment]
Found it, thanks!

Turns out I didn't test the migration to [libite](https://github.com/troglobit/libite) properly. Sorry for that! The OpenBSD version of `pidfile()` is incompatible with the Inadyn 1.xx series.  Will revert that change and push a fix soon.

Do you need a proper release, or can you live with a patch, or even use the GIT master for a while?  I'm otherwise planning to incorporate a few more fixes before doing a proper release ...

**Comment by daersc** [comment]
Thank you for your rapid answer! A patch will be fine :-)

**Comment by troglobit** [comment]
No problem, thank you for the report! :smiley: 

I couldn't figure out how to get a raw patch from GitHub, but here's a link to my personal (backup) repo.  If you want a minimal patch, then the last part, patching only `src/os.c` should be sufficient for your needs:

> http://git.troglobit.com/inadyn.git/commitdiff_plain/802ef1b
