### ISSUE TITLE
Failed connecting to remote server: Operation now in progress

### ISSUE THREAD

**Issue by Adlbert** [troglobit/inadyn#132]
-I read all your previous post but still can't make inadyn to connect. I dunno which server is meant.

-i install inadyn via: apt-get install inadyn

-i replace the config with:

system default@freedns.afraid.org
     #ssl
     username Adlbert
     password Kilik0708
     alias team-stronach-gaming.chickenkiller.com

I have to comment ssl cause otherwise it wont work. I have openssl installed.

And here is the log:

Wed Jun 29 13:24:31 2016: Inadyn version 1.99.4 -- Dynamic DNS update client.
Wed Jun 29 13:24:32 2016: Resolving hostname team-stronach-gaming.chickenkiller.                                                                                        com => IP# 62.178.38.71
Wed Jun 29 13:24:32 2016: Checking for IP# change, connecting to checkip.dyndns.                                                                                        org(216.146.38.70)
Wed Jun 29 13:24:52 2016: Failed connecting to remote server: Operation now in progress
Wed Jun 29 13:24:52 2016: Will retry again in 120 sec...
^CWed Jun 29 13:26:51 2016: STOP command received, exiting.

**Comment by troglobit** [comment]
Inadyn v1.99.4 is a very old release. I've made many releases since.

For software  installed as package via your distribution you should report the bug to them, not me ... I have no say in what the distributions pacakge.  I've tried to to convince Debian to upgrade to a newer version, even added SSL support (which your version does not have), but no lock so far.  I will try again when I've released Inadyn v2.0 which is now being tested here on GitHub.

Please report the bug to Debian, or Ubuntu, or whatever distribution you are using.
