### ISSUE TITLE
Build/Execution problems Debian Jessie

### ISSUE THREAD

**Issue by Phiber2000** [troglobit/inadyn#135]
I tried to use the v2.0-rc1 with Debian Jessie and got it compiled using libite build from source and libconfuse v3 installed from Debian stretch packages.

I used the libconfuse packages from Debian stretch because I didn't get libconfuse installed from source so that inadyns make execution detected it.
With the libconfuse packages, inadyn compiled and installed properly! But running inadyn leads to the "error while loading shared libraries: libconfuse.so.1" error...
I think, the library is properly installed and "pkg-config --libs --static --cflags libconfuse" gives me the correct answer.

I had to downgrade inadyn to v1.99.15 build from source, too. I think works because it doesn't need libconfuse.

Questions:
- Wouldn't it be possible to include the library sources as you did before with libite? It would be very comfortable for all who build from sources... Btw.: Why did you remove it?
- If not, does anyone have a idea what's wrong or has a solution?

**Comment by troglobit** [comment]
When installing libraries from source you need to run `ldconfig` to update the .so cache.  Use `ldconfig -v` to see what, and where, libraries are installed.  Useful also to check for duplicates which may sometimes cause conflicts on a system.

I have not tried installing the Debian Stretch version of libConfuse on my Jessie installation, but installing from source (to `/usr/local`) works and `inadyn` runs happily with that. So I think there may be something wrong with the libconfuse package, or your installation that disagrees with it.

Now, regarding your specific question of `libite` now being distributed separately. Sure it is possible to include all sources required by Inadyn, but that turned out to be a lot of work, and I'm only one unpaid person. So for maintenance reasons I have chosen to break out every dependency and maintain them separately. This is also the recommended way to work with libraries in Linux/GNU where I do most of my work.

**Comment by Phiber2000** [comment]
Thanks for your answer and help. I'll close here and try it as soon as possible and give a short report!

**Comment by Phiber2000** [comment]
You were right. Another `ldconfig` after install of libconfuse did the trick.
I was used to that this is done by make target... Thanks!
