### ISSUE TITLE
Does inadyn require libite?

### ISSUE THREAD

**Issue by ysc3839** [troglobit/inadyn#167]
I got this error when building inadyn.
```
checking for lite... no
configure: error: Package requirements (libite >= 1.5.0) were not met:
No package 'libite' found
```
But there's no any include in source code.

**Comment by troglobit** [comment]
Ah, no ... that was removed in e27bfbf. Thanks for the heads-up, fxing!

**Comment by troglobit** [comment]
Um, actually.  It looks like It really was removed in e27bfbf.  Try running `./autogen.sh` again, it updates the configure script.

**Comment by ysc3839** [comment]
I'm using [v2.1](https://github.com/troglobit/inadyn/releases/tag/v2.1) release.

**Comment by troglobit** [comment]
Ah, well in the last release libite was a requirement.  (Turned out to be a hassle even for me.)

New releases can be made with the *GNU Configure & Build* standard build target `make dist` or my own shortcut `make release`.  Although I would recommend against rolling your own release, I'm planning a release any day now. Just waiting for a few of my own tests to complete.

**Comment by ysc3839** [comment]
Just for a test. I'm trying to compile inadyn for a router firmware.

**Comment by troglobit** [comment]
OK, good luck mate! :)

Be sure to report any problems.  I haven't run `make distcheck` in a while now, which is one of the steps on my checklist for a new release.

**Comment by ysc3839** [comment]
Just tested. No issue.

**Comment by troglobit** [comment]
@ysc3839 Thanks for verifying! :-)
