### ISSUE TITLE
how to use inadyn in the windows os?

### ISSUE THREAD

**Issue by anlexN** [troglobit/inadyn#184]
I have already downloaded this release v2.2.1, but i can't find something like inadyn.exe, how to use inadyn?
I'm windows x64 os
![default](https://user-images.githubusercontent.com/8686739/32327921-350d1050-c013-11e7-8515-3d68761de2b4.PNG)

**Comment by ysc3839** [comment]
This is source code. Not binary.
Inadyn is designed for *nix systems. It cannot run on Windows.

**Comment by troglobit** [comment]
There have been reports about people successfully running Inadyn in Cygwin, but no, it's like @ysc3839 says. This is a command line tool mostly geared towards UNIX systems, distributed as source since most Linux/*BSD distributions build and package it themselves for further distribution.

There are probably other tools, more suitable for running in Windows.

(Closing issue without further action)
