### ISSUE TITLE
Missing debian/ directory in release tarballs

### ISSUE THREAD

**Issue by acolomb** [troglobit/inadyn#188]
Are you not distributing the `debian/` subdirectory in releases by intention? I was personally confused by reading something about integrated debian build files in the ChangeLog, but not finding them in the current release.

Automake's `EXTRA_DIST` setting comes to mind, but I'm not sure if that's how it should be handled.

**Comment by troglobit** [comment]
The `debian/` directory is not supposed to be distributed in the tarball.  Debian maintainers prefer to manage that directory themselves (usually because they need to support multiple distribution releases) and upstream packages that distribute a `debian/` themselves create an unnecessary hassle for Debian maintainers.

So it is as a courtesy to Debian/Ubuntu that we don't distribute that directory.

**Comment by troglobit** [comment]
@acolomb I hope my answer was to your satisfactory. Please let me know so we can close the issue, or if something needs to clarified.

**Comment by acolomb** [comment]
Yes, thanks for your explanation.
