### ISSUE TITLE
Packages of new version for Debian/Ubuntu?

### ISSUE THREAD

**Issue by teneri66** [troglobit/inadyn#199]
Even newest Ubuntu release uses version 1.99.4. It would be evolve project much further if newer version is provided into repos.

**Comment by troglobit** [comment]
+1

We in the upstream Inadyn project have little to no influence over various Linux/UNIX distributions. Please file a bug report with Debian and/or Ubuntu instead.  I [did so myself](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846935) a while back, but it seems the maintainer [has orphaned](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879872) the package.  Maybe if more users, like yourself, show interest in the package a Debian Developer may pick it up.

**Comment by cmatsuoka** [comment]
A newer version is available as a snap package: https://snapcraft.io/inadyn

**Comment by troglobit** [comment]
@cmatsuoka Cool, thanks for the update! :-)

**Comment by cmatsuoka** [comment]
@troglobit I'm using the snap package and it's working well for dynv6 and nsupdate (but I wasn't able to update IPv6 in dyn, I'll check that more carefully later). If you're interested in always having the latest version available, there's a mechanism to automatically build snap packages triggered by a github push (the current owner of the snap package is Snapcrafters, but they can transfer the ownership to upstream to enable this auto-build mechanism).

**Comment by troglobit** [comment]
@cmatsuoka Interesting!  I'm considering adopting the Debian package, but a snap build would have a quicker turnaround.  I'll have to get back to you on this, thanks!

**Comment by Makishima** [comment]
In my opinion problem with snap that it is bigger, because it contains all the files. So it is not suitable for VPS with small disk space.

**Comment by cmatsuoka** [comment]
@Makishima Indeed. The snap package works very well in regular systems where space is not a concern, but minimal environments might require a different solution.

**Comment by troglobit** [comment]
Good point @Makishima, thanks!

We'd definitely need someone to step up as new Debian maintainer.  Usually I look to myself in those situations, but I'm just starting to learn the ropes, so anyone else with an interest in Inadyn would be preferable.

**Comment by FedericoCeratto** [comment]
I'm setting up a repo on Salsa to maintain the package :)

**Comment by troglobit** [comment]
@FedericoCeratto --> https://github.com/troglobit/inadyn/blob/master/inadyn.service.in

**Comment by FedericoCeratto** [comment]
Packaging repo: https://salsa.debian.org/debian/inadyn
I had to patch out something to support systemd: https://salsa.debian.org/debian/inadyn/tree/master/debian/patches

**Comment by troglobit** [comment]
@FedericoCeratto Hmm, that shouldn't be necessary, the postinst should create and chown at least the cache¹ directory.  The /run sub-directory is worse, since it's tmpfs. Maybe systemd has some magic you could use for that?

Also, I see you cloned the old `debian/` packaging by @taem. Any reason you opted for that rather than mine?  My version has the finalized version to create an initial /etc/inadyn.conf using the debconf wizard framework.
____
¹) The cache directory is *really* important. If inadyn cannot save the result of a DDNS server update it will send more updates than are necessary and some DDNS providers are known to block users that update too often without any actual IP address change.

**Comment by troglobit** [comment]
@FedericoCeratto I haven't heard back from you in a while, how is the packaging efforts going?  Since last time I've added support for `--no-pidfile` in 98944a0.  It will make it harder for users who want to sent signals to inadyn, e.g., `USR1` or `USR2`, but now it's there if you'd like to use it.  That in combination with `-n` and omitting `-s`, and recent patches to prevent `chown()` should fulfill your requirements.

**Comment by FedericoCeratto** [comment]
@troglobit Thanks, the changes could help - also I'm happy to see that the project is alive. Are you planning to release the new changes?

**Comment by troglobit** [comment]
@FedericoCeratto Yes, the plan was to release v2.6 today (CET), I'll see if I make it otherwise it'll be out tomorrow.

**Comment by troglobit** [comment]
Done, finally.  The [v2.6 release](https://github.com/troglobit/inadyn/releases/tag/v2.6) of In-a-dyn can be installed like this:

```sh
curl -sS https://deb.troglobit.com/pubkey.gpg | sudo apt-key add -
echo "deb [arch=amd64] https://deb.troglobit.com/debian stable main" | sudo tee /etc/apt/sources.list.d/troglobit.list
sudo apt-get update && sudo apt-get install inadyn
```
