### ISSUE TITLE
no-ip: invalid base64 encoding of passwords with special characters

### ISSUE THREAD

**Issue by hancockks** [troglobit/inadyn#211]
# cat /usr/local/etc/inadyn.conf
period = 432000
provider default@no-ip.com {
    username = myusername
    password = password#hash
    hostname = { "test.com" }
}
inadyn[5411]: Sending alias table update to DDNS server: GET /nic/update?hostname=test.com&myip=XX.XX.XX.XX HTTP/1.0
Host: dynupdate.no-ip.com
Authorization: Basic bXl1c2VybmFtZTpwYXNzd29yZA==
User-Agent: inadyn/2.2 https://github.com/troglobit/inadyn/issues

inadyn[5411]: Successfully sent DDNS update using HTTPS!
inadyn[5411]: DDNS server response:

Note two errors here:

1. base64 decode of the Authorization: Basic decodes to "myusername:password" -- it's missing everything hash and later.
2. The DDNS server response isn't being shown.  It's returning a 401 error

Additionally, I cannot verify whether the username:password@ is being correctly encoded in the URL.  Any special characters in the password would have to be html escaped, in the above case http://myusername:password%23hash@dynupdate.no-ip.com

**Comment by troglobit** [comment]
Try putting the password in double quotes, like this:

    password = "password#hash"

I recently commented out the encoded debug message you need.  But if you run an earlier version it should be logged if you run inadyn with `-l debug`.

**Comment by dakaix** [comment]
I'm seeing the same behaviour, no DDNS response and there's no change actioned on No-Ip's side. However unlike hancockks I'm using a password with no special characters, plain alpha numeric.

This had been working fine for the last few months, is there an API change on No-IP's side perhaps?

**Comment by troglobit** [comment]
@dakaix Have you tried running inadyn in the foreground with `-l debug`?  You should also check your account at No-IP, some providers block accounts/hostnames that update too often.

The API is defined here, https://www.noip.com/integrate/request and it looks to me that it's the same as before. Exact same as Dyn et al.  The code is in `plugins/dyndns.c` and `plugins/common.c`.

**Comment by hancockks** [comment]
@dakaix I had the same results after changing my password to work around the issue (before the quotes suggestion was posted). I'm not sure if it's a latency issue between the back end and the UI...

**Comment by troglobit** [comment]
@dakaix I think I'm starting to understand what's going on here. I'm assuming you're using the OpenSSL backend and not GnuTLS?  OpenSSL is the only code path that seems plausible, because ...

... The transaction with the server is in two phases: 1) send the HTTP GET string, and 2) wait for and receive reply.

After 1) there is the debug message "Successfully sent ...", this is printed on success.  But in 2) there no such message, which by looking at the code (openssl.c) there should be, which in turn seems to indicate there was an error.

Unfortunately Inadyn doesn't print the OpenSSL error, that code path is still TODO.  Either way, the front-end should check the reply from the back-end only attempt to show the reply on success.

**Comment by troglobit** [comment]
I've pushed some changes related to this. Would be great if someone could test it.

See https://github.com/troglobit/inadyn/#building-from-git for details on building from Git.

**Comment by troglobit** [comment]
Closing due to lack of feedback to fixes.
