### ISSUE TITLE
Update fail for dynv6

### ISSUE THREAD

**Issue by cmatsuoka** [troglobit/inadyn#235]
Nsupdate just informed me that:

> Your update client sent 83 faulty updates since we last checked.
> We have reset the faults counter to 0 now, but we are rejecting updates
> for this host until you resolve the issue.

Looking at the log messages, it seems that the problem is caused by a misinterpretation of dynv6 return status:

```
2019-02-12T10:44:55Z inadyn[4200]: In-a-dyn version 2.5 -- Dynamic DNS update client.
2019-02-12T10:44:57Z inadyn[4200]: Update forced for alias myhost.dynv6.net, new IP# x.y.z.w
2019-02-12T10:44:58Z inadyn[4200]: Fatal error in DDNS server response:
2019-02-12T10:44:58Z inadyn[4200]: [200 OK] addresses unchanged
2019-02-12T10:44:58Z inadyn[4200]: Error response from DDNS server, exiting!
2019-02-12T10:44:58Z inadyn[4200]: Error code 48: DDNS server response not OK
```

**Comment by troglobit** [comment]
@cmatsuoka Good catch, a possible fix is available in PR #236.  Would be very appreciated if you could have a look at it.

**Comment by cmatsuoka** [comment]
@troglobit I confirm that PR #236 seems to have fixed the issue. Updates to dynv6 are being processed without error messages.

(Now it would be a good time to push this commit and have the snap package updated automatically! :D)

**Comment by troglobit** [comment]
@cmatsuoka Thanks, merging!

(He he ;-)

**Comment by dprus** [comment]
This issue seems to be back again. I'm seeing the exact same issue now with the latest 2.6-dev:

> inadyn    | inadyn[1]: In-a-dyn version 2.6-dev -- Dynamic DNS update client.                                                                                                                  
inadyn    | inadyn[1]: Update forced for alias router.home.powell.dev, new IP# x.x.x.x
inadyn    | inadyn[1]: Update forced for alias server.home.powell.dev, new IP# x.x.x.x
inadyn    | inadyn[1]: Update forced for alias login.home.powell.dev, new IP# x.x.x.x
inadyn    | inadyn[1]: Fatal error in DDNS server response:                                                                                                                                    
inadyn    | inadyn[1]: [200 OK] addresses unchanged                                                                                                                                            
inadyn    | inadyn[1]: Error response from DDNS server, exiting!                                                                                                                               
inadyn    | inadyn[1]: Error code 48: DDNS server response not OK
