### ISSUE TITLE
Unable to install inadyn 2.9.0 on Ubuntu 20.04, missing dependency on libnettle6

### ISSUE THREAD

**Issue by cjbaghl** [troglobit/inadyn#366]
Attempted to update inadyn 2.8.1 to 2.9.0.  Failed due to a dependency on libnettle6.
I uninstalled inadyn and went thru the recommended install instructions.
Received the following during apt install:
root@server:/etc/apt/sources.list.d# apt install inadyn
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 inadyn : Depends: libnettle6 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by troglobit** [comment]
The .deb is built on an older Debian 10 system. Previously that ensured support for Debian and Ubuntu systems alike.  However, in eea6a58 we added support for optimized SHA1 and MD5 functions from libnettle, which is of ABI version 6 in Debian 10 and 7 in Ubuntu 20.04.  

To support your installation you can rebuild the .deb from the release tarball.

A future release may make libnettle optional and restore support for newer systems.  This project, and its maintainer, can unfortunately not provide pre-built .deb files for all possible operating systems.  Hopefully the new downstream maintainer can keep Inadyn up to date in debian -> https://packages.debian.org/sid/inadyn so it eventually makes its way to Ubuntu.  Then I can drop inadyn from deb.troglobit.com.

**Comment by acolomb** [comment]
Would you consider at least making the "source packages" available in your APT repository? Such that this command will work when having the corresponding `deb-src` line in sources.list:

    apt source inadyn

**Comment by troglobit** [comment]
@acolomb in my current development flow I've automated everything using GitHub actions, except for building the .deb package.  That's the only step that's made by hand using a few scripts I've set up, and it doesn't generate the source package, nor do I have that infrastructure set up.  I understand where you're coming from, but as I've mentioned before to you, I'm a single person with very small resources to maintain a full-blown deb infrastructure.  The pre-built package I provide was supposed to be a courtesy while there was no official Debian packaging. Now there is, so I suggest you push for updates downstream instead, or (as I mentioned above) build from the GitHub sources right here.

**Comment by troglobit** [comment]
I've looked into this mess a bit further now.  Turns out Debian 10 (Buster, a.k.a "oldstable") had libnettle6 (ABI version 6), which my .deb-build server runs -- the idea was to support as many distros as possible.  The current Debian 11 (Bullseye, stable) has libnettle8, while Ubuntu 20.04 and Linux Mint 20.x all have libnettle7. 

This (not new) dependency comes from our having to build the .deb package with GnuTLS due to the licensing issues with OpenSSL.  Since the .deb I'm providing is *not* in Debian, I could change the package to use OpenSSL instead. The libssl1.1 package seems to be available equally across the Debian and Ubuntu releases, so that's a positive takeaway at least. However, changing to OpenSSL in a patch release (Inadyn 2.9.1) feels risky and will likely make a lot of other people angry.

This leads me to the only logical conclusion, which is to indefinitely suspend providing pre-built .deb files for Inadyn.  The runtime dependencies in this project make it too much a problem to support.  Also, as a hat-tip to the new Debian maintainer, I'll be moving the `debian/` subdirectory to a separate (debian) branch to ease GIT packaging on salsa.debian.org.  I'm well aware that all this may cause some more anger or frustration, but I hope you understand that even I have limits to the amount of waken hours in a day.

**Comment by acolomb** [comment]
No worries, completely understand your reasoning.  Great to see continued work on the offical Debian package by the way! I hope it will be as easy to build from Git as it was up to now.

**Comment by acolomb** [comment]
I just noticed the README still contains instructions involving the APT repository.

**Comment by troglobit** [comment]
Thanks for the heads up, I’ll clean it up tomorrow before $DAYJOB.
