### ISSUE TITLE
Problems when using a custom service

### ISSUE THREAD

**Issue by poinu** [troglobit/inadyn#91]
First of all I would like to thank you for investing your time in working on an open source project such as this. Second, I would like to comment some issues I have detected when updating inadyn to one of its most recent versions.

For the 1.99.4 version, on a Debian Jessie.

When running inadyn specifying a custom service with `inadyn -S custom@http_svr_basic_auth` (as seen in the manpage) the following error shows up:
>Fri May  8 12:37:58 2015: Cannot find DDNS provider custom@http_svr_basic_auth, check your spelling.
>Fri May  8 12:37:58 2015: Error parsing option -S
>Fri May  8 12:37:58 2015: Failed starting daemon: >RC_CMD_PARSER_INVALID_OPTION_ARGUMENT

However, when running with `inadyn -S custom@http_srv_basic_auth` (notice svr changed to srv), I don't get this error anymore.

Another issue is that, when specifying a custom service, I am forced to specify a `username` and a `password`, otherwise I get this error:

>Fri May  8 13:21:05 2015: Missing username in account 1
>Fri May  8 13:21:05 2015: Missing password in account 1
>Fri May  8 13:21:05 2015: No valid DDNS setup exists.
>Fri May  8 13:21:05 2015: Failed starting daemon: >RC_DYNDNS_INVALID_OR_MISSING_PARAMETERS

I shouldn't need to specify neither username nor password as, in this case, they are passed to the server directly in the URL (using -U flag). Specifying those wasn't required in previous versions.

Something similar happens with the `alias`, I am forced to specify one even though the hostname should be passed through the URL in the same way as the username or the password. However, this did happen in previous versions.

At last, when running inadyn using this workaround (replacing those required parameters with random words or empty strings):

`inadyn -S custom@http_srv_basic_auth -N dynamicdns.park-your-domain.com -U "/update?domain=my.domain&password=mypassword&host=myhostname" -u user -p password -a ""`

The IP is successfully updated in the server. However, the inadyn daemon reports the following error and stops running:

>Fri May  8 14:54:30 2015: Failed resolving hostname : Name or service not known
>     [...]
>Fri May  8 14:54:31 2015: Fatal error in DDNS server response:
>Fri May  8 14:54:31 2015: [200 OK] <?xml version="1.0"?>\<interface-response>\<Command>SETDNSHOST\</Command>\<Language>eng\</Language>\<IP>My IP :)\</IP>\<ErrCount>0\</ErrCount>\<ResponseCount>0\</ResponseCount>\<Done>true\</Done>\<debug>\<![CDATA[]]>\</debug>\</interface-response>
>Fri May  8 14:54:31 2015: Error response from DDNS server, exiting!
>Fri May  8 14:54:31 2015: Failed starting daemon: RC_DYNDNS_RSP_NOTOK

It is logical that it fails resolving the hostname as there is no hostname (empty string) but I belive it shouldn't be reporting a fatal error on the sever response when the response contains `<ErrCount>0</ErrCount>`.

This last issue makes the daemon unusable when it comes to custom services, and a Cron job or another alternative needs to be configured.

It would be nice if those issues could be solved, otherwise I think that the 'custom service' feature would not be fully functional. Thank you for your time!

**Comment by troglobit** [comment]
Hi, sorry for the late reply!

First of all, bug reports for distribution packaged versions of software should always go through that distribution.  They may have applied patches and/or provide support that we as upstream don't know of.

Now, I am painfully well aware of the limitations of the custom service.  From time to time I've considered removing it, because it's very difficult to support.  I do not have access to all the worlds different DDNS providers.

In your case I suspect it would be easier to simply write a small plugin for your DDNS provider instead of trying to bend custom to fit your needs. 

However, if you (or someone else) have a patch to address the problems you've mentioned above, I'm more than willing to add it to Inadyn.  So I'm going to leave this issue open, for anyone to pitch in.

Cheers
 /Joachim

**Comment by troglobit** [comment]
Have looked into this a bit more now.

1. The `custom@http_srv_basic_auth` is for using HTTP basic authentication, using base64 encoded `username:password`.  We should probably support a `custom@http_srv_no_auth` ...
2. I will however lax the requirement for always supplying a username/password to `custom@`, it is then up to the server if it accepts base64 encoded "":""
3. The `alias` setting is required.  It is both used internally for tracking time for update etc. and
is also what is appended to the HTTP GET URL sent to the server on updates. In your case your could set

        alias myhostname
        server-url /update?domain=my.domain&password=mypassword&host=

  Unless `myhostname` was one of those "random words" you talked about, then you could change the config to this:

        alias my.domain
        server-url /update?password=mypassword&domain=

4. In newer versions of Inadyn, newer than what Debian/Ubuntu currently has, the generic plugin (which handles `custom@`) also looks for the string `true`.
5. Also, I've never seen `<ErrCount>0</ErrCount>` reported from any other server, so that is not something I'd expect Inadyn to know about.  Again, maybe a dedicated plugin for your DDNS provider is a better option?

**Comment by troglobit** [comment]
In Inadyn v1.99.14 (just released) there is now support for `append-myip`, which can be used with custom DDNS providers.  See the README, or the man pages, for more info on this, quite handy.

I've also updated the README more about custom DDNS provieders.  Hope this helps!

**Comment by JurekRaben** [comment]
There is a spelling error in "http_svr_basic_auth", it needs to be "http_srv_basic_auth" instead.  srv vs svr.  Since svr looks correct to me, the spelling problem is inside the source?

**Comment by troglobit** [comment]
@JurekRaben This is an issue closed almost three years ago for a very old version of Inadyn.  If your problem pertains to a version packaged by a Linux distribution, I suggest you report it there.  Current Inadyn releases have no such mechanism anymore.

**Comment by JurekRaben** [comment]
Well hard to know such differences, if you are not the developer yourself. Would be helpful, if you were writing about these differences in versions available in the readme. Kind of annoying to find proper info in Linux world, if everybody only cares for his/her own microcosmos - not you, I mean in general :)

**Comment by troglobit** [comment]
@JurekRaben I understand your problem, it's simply just not realistic to document all differences to all previous versions from the current one.  All major changes are however denoted in the ChangeLog, which most well-maintained projects should have.
